send_command:
  name: "Send RCON Command"
  description: "Send an RCON command to the selected server."
  fields:
    server:
      name: "Server"
      description: "Nickname or ID of the target server."
      selector:
        text: {}
    command:
      name: "Command"
      description: "The command to send."
      selector:
        text: {}
